name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install --save --legacy-peer-deps


    - name: Build
      run: |
        npm run build

    - name: Deploy to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username:  ${{ secrets.USER }}
        key:  ${{ secrets.KEY }}
        port:  ${{ secrets.PORT }}
        
        source: build/
        target: /var/www/html/

    - name: Install Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username:  ${{ secrets.USER }}
        key:  ${{ secrets.KEY }}
        port:  ${{ secrets.PORT }}}
        
        script: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx
