
name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
         npm install --save --legacy-peer-deps

    - name: Build
      run: |
        npm run build

    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -xvf deploy.tar ../build/
        cd /home/ubuntu/destination/folder/
        tar -xvf deploy.tar
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username:  ${{ secrets.USER }}
        key:  ${{ secrets.KEY }}
        port:  ${{ secrets.PORT }}
        source: "deploy.tar"
        target: "destination/folder"
    - name: Extract
      run: |
        tar -xvf deploy.tar
